### ISSUE TITLE
BLOCKER! Issue started from yesterday

### ISSUE THREAD

**Issue by Blackening999** [ciena-blueplanet/ember-prop-types#39]
loader.js:219 Uncaught Error: Could not find module `dummy/config/environment` imported from `ember-get-config/index`

I've started seeing this error after updating bower/npm. Seems like some upgrade spoiled the party

**Comment by null-null-null** [comment]
This definitely looks related to a change I made for `ember-get-config v0.1.4`, but that being said, I'm not able to replicate it. Looks like tests are passing in this repo, and when I make a fresh app that uses `ember-prop-types`, that works too. Do you happen to have a public repo that this is failing in?

**Comment by sandersky** [comment]
@Blackening999 it would be helpful if you can provide the dependencies in your `package.json` and `bower.json` so I can try to reproduce. As @null-null-null suggested if this is a public repo you can just point us to it. Thanks.

**Comment by Blackening999** [comment]
Hey, guys! Nice to see instant feedback.
So in human words: nice day, birds signing, one guy making deploy with nothing changed in terms of dependencies. BOOM! shaka laka :) deploy passed, production dead... I see the error in console.log. Most frustrating this thing haven't prevented deploy to pass! It just passed it and then showing the emberJS (undefined class) error.

Here are my dependencies:
package.json:

```json
{
  "name": "NAME",
  "version": "0.0.0",
  "description": "NAME",
  "private": true,
  "directories": {
    "doc": "doc",
    "test": "tests"
  },
  "scripts": {
    "start": "ember server",
    "build": "ember build",
    "test": "ember test"
  },
  "repository": "",
  "engines": {
    "node": "4.2.2",
    "npm": "2.14.3"
  },
  "author": "",
  "license": "MIT",
  "devDependencies": {
    "active-model-adapter": "2.0.3",
    "broccoli-asset-rev": "^2.2.0",
    "ember-ajax": "2.4.1",
    "ember-async-button": "1.0.0",
    "ember-browserify": "1.1.9",
    "ember-can": "0.8.0",
    "ember-cli": "2.5.1",
    "ember-cli-app-version": "^1.0.0",
    "ember-cli-babel": "^5.1.5",
    "ember-cli-clock": "2.1.1",
    "ember-cli-content-security-policy": "0.5.0",
    "ember-cli-copyable": "0.9.6",
    "ember-cli-custom-assertions": "0.0.4",
    "ember-cli-dependency-checker": "^1.2.0",
    "ember-cli-file-picker": "0.0.9",
    "ember-cli-flot": "0.0.3",
    "ember-cli-htmlbars": "^1.0.1",
    "ember-cli-htmlbars-inline-precompile": "^0.3.1",
    "ember-cli-inject-live-reload": "^1.3.1",
    "ember-cli-mirage": "0.2.0",
    "ember-cli-moment-shim": "2.0.0",
    "ember-cli-qunit": "^1.2.1",
    "ember-cli-release": "0.2.8",
    "ember-cli-sass": "5.3.1",
    "ember-cli-sri": "^2.1.0",
    "ember-cli-stripe": "0.4.0",
    "ember-cli-uglify": "^1.2.0",
    "ember-computed-decorators": "0.2.2",
    "ember-data": "2.5.3",
    "ember-disable-proxy-controllers": "1.0.1",
    "ember-export-application-global": "^1.0.4",
    "ember-faker": "1.1.0",
    "ember-frost-core": "0.11.10",
    "ember-frost-tabs": "2.0.1",
    "ember-group-by": "0.0.2",
    "ember-infinity": "0.2.3",
    "ember-load-initializers": "^0.5.0",
    "ember-lodash": "0.0.9",
    "ember-modal-dialog": "0.8.4",
    "ember-moment": "6.1.0",
    "ember-one-way-controls": "0.8.2",
    "ember-pikaday": "2.1.0",
    "ember-power-select": "0.10.10",
    "ember-pusher-guru": "git://github.com/Blackening999/ember-pusher-guru",
    "ember-resolver": "2.0.3",
    "ember-scroll-box": "1.0.2",
    "ember-select-2": "1.3.0",
    "ember-simple-auth": "1.1.0",
    "ember-stripe-service": "^3.0.0",
    "ember-truth-helpers": "1.2.0",
    "loader.js": "^4.0.0",
    "minimist": "^1.2.0",
    "svg4everybody": "2.0.3",
    "torii": "0.8.0"
  }
}

```


Bower json:

```json
{
  "name": "NAME",
  "dependencies": {
    "jquery-ui": "~1.11.4",
    "ember": "2.5.1",
    "ember-cli-shims": "^0.1.0",
    "ember-cli-test-loader": "0.2.2",
    "ember-qunit-notifications": "0.1.0",
    "jquery": "^1.11.3",
    "blob-polyfill": "^1.0.20150320",
    "ember-qunit": "0.4.20",
    "qunit": "~1.22.0",
    "bootstrap-sass": "twbs/bootstrap-sass#3.3.4",
    "jquery-knob": "1.2.13",
    "font-awesome": "4.5.0",
    "hubspot-messenger": "HubSpot/messenger#1.4.1",
    "pretender": "~0.10.1",
    "jquery.atwho": "~0.5.1",
    "fullcalendar": "2.2.3",
    "pace": "1.0.2",
    "moment": "^2.8.0",
    "raven-js": "~1.1.18",
    "summernote": "0.7.3",
    "lodash": "^4.10.0",
    "moment-duration-format": "~1.3.0",
    "flot": "~0.8.3",
    "flot.tooltip": "~0.8.5",
    "select2": "3.5.2",
    "moment-timezone": "^0.5.0",
    "Faker": "^3.1.0",
    "dinosheets": "0.1.1",
    "jquery-mockjax": "2.0.1",
    "perfect-scrollbar": ">=0.6.7 <2.0.0",
    "pikaday": "^1.4.0",
    "pusher": "3.0.0",
    "pusher-test-stub": "2.0.0"
  },
  "resolutions": {
    "qunit": "~1.22.0",
    "jquery": "~1.12.4"
  }
}
```

The another scary thing I wasn't able to find where I can freeze the package! :)

Would be much appreciated if I could tell customers that everything will be ok tomorrow :)

Thank you!

**Comment by null-null-null** [comment]
@Blackening999 I think I know what might have caused this, so I just published a bug fix version of `ember-get-config`. Would you mind nombom-ing to see if it fixes the issue? If not, I could use some additional information about your deps. In particular, could you search your `node_modules` directory for `ember-get-config`. (Searching that directory can take a solid minute, especially when you've got a lot of deps like this.) In particular, look out for cases where `ember-get-config` is deeply nested within other modules. If I could find out where it's getting used, I could try to recreate the issue locally.

**Comment by sandersky** [comment]
1. I ran the following:

  ```bash
  npm install -g ember-cli@2.5.1 phantomjs
  ember new my-test
  cd my-test
  ```

2. I updated my `package.json` and `bower.json` with the dependencies provided in the comment above.

3. I ran:

  ```bash
  rm -rf node_modules bower_components
  npm install && bower install
  ember install ember-cli-mirage
  mv app/styles/app.css app/styles/app.scss
  npm test
  ```

  and the tests ran without errors.

> Note: I did this on Node version `5.11.0`.

**Comment by sandersky** [comment]
@Blackening999 After trying the above I went ahead and release version `2.4.1` of `ember-prop-types` which uses the new version of `ember-get-config` just released by @null-null-null in case that is the cause of your issue. Please let me know if this addresses your issue so we can get this Github issue resolved/closed. Also thank you @null-null-null for jumping on this issue, I'm amazed that you jumped on it so quickly when it wasn't even file on your project :+1:.

**Comment by Blackening999** [comment]
@sandersky 
@null-null-null 
Unfortunately it doesn't solve my case. 
I've reinstalled deps with node 5.11.0 - the same error

**Comment by Blackening999** [comment]
https://github.com/cibernox/ember-basic-dropdown/blob/master/package.json
"ember-get-config": "0.0.2",

ember-prop-types :)
0.15

**Comment by Blackening999** [comment]
Where ember-prop-types user

ember-frost-core
https://github.com/ciena-frost/ember-frost-core
"ember-prop-types": "^2.0.0",

**Comment by Blackening999** [comment]
@null-null-null 
@sandersky 

Issue found
when I've deleted ember-frost-core and ember-frost-tabs it worked.

Let me know what should I do in order to solve that issue ASAP.
Would be really, really MUCH appreciated if I can do it without forking those libs and forcing the ember-prop-types to 0.13 ;)

**Comment by sandersky** [comment]
So you are saying your problem is the newer version of `ember-prop-types`? I'm still not sure it is clear what the root cause of your problem is and pinning things back to older versions doesn't seem to be the ideal solution to me. It'd be nice to actually understand where the underlying issue is coming from so it can be fixed. `ember-frost-core` which I am developer of uses the latest `ember-prop-types` and both seem to work fine. You mentioned you are using `ember-basic-dropdown` which requires an older version of `ember-get-config`. So rather than removing `ember-frost-core` from your build to get things working, what happens if you remove `ember-basic-dropdown`?

**Comment by null-null-null** [comment]
@Blackening999 I haven't been able to replicate this locally, even when creating a fresh app with your deps. Still, this issue is clearly linked to a recent I update I made to `ember-get-config`, which concerns me. Are you on the Ember Community Slack channel? We might be able to debug this faster if we take the conversation there. Even better, a screenshare would great.

**Comment by Blackening999** [comment]
For sure, it isn't ideal solution to downgrade anyway. However, my production is down, so this is only one logical solution at that moment.

sure we can, how can I join it?

http://prntscr.com/c5psk6

**Comment by null-null-null** [comment]
@Blackening999 https://ember-community-slackin.herokuapp.com/

**Comment by Blackening999** [comment]
The ember-basic-dropdown manages through "ember-power-select": "0.10.10"
Deleting which doesn't make any difference.

**Comment by Blackening999** [comment]
Thank you for link!

**Comment by Blackening999** [comment]
I'm in same nickname but lowercased
(delete this once it has been read)

**Comment by sglanzer** [comment]
I've merged @null-null-null's fix to `ember-frost-core` - let us know if that unblocks you
